eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

logging:
  file:
    name: C:/Users/prasa/Documents/Project/springboot-microservice-hotel-management/elk-stack.log